apiVersion: v1
kind: Service
metadata:
  name: {{ include "docrag.fullname" . }}-backend
  labels:
    app: docrag-backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      name: http
  selector:
    app: docrag-backend
