{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "docrag.fullname" . }}-servicemonitor
  labels:
    app: docrag-backend
spec:
  selector:
    matchLabels:
      app: docrag-backend
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end }}
